<?php
$hardcoded_restaurantes = array(
  array('title'=>'Manolo', 'content'=>'', 'cocina'=>'', 'horario'=>'', 'reserva_tipo'=>'web', 'reserva_val'=>'', 'menu'=>'', 'thumb'=>''),
  array('title'=>'Valentina Cocina Contemporánea', 'content'=>'Experiencia sensorial que combina técnicas culinarias de vanguardia con los mejores ingredientes de origen. Cortes selectos, pescados de importación y coctelería de autor en una atmósfera sofisticada y vibrante dentro de Casa de Piedra.', 'cocina'=>'Alta Cocina Contemporánea & Asador', 'horario'=>'', 'reserva_tipo'=>'web', 'reserva_val'=>'https://grupomrl.com.mx/2025/valentina/', 'menu'=>'https://grupomrl.com.mx/2025/wp-content/uploads/2026/05/menu-Valentina-Leon.pdf', 'thumb'=>''),
  array('title'=>'Casa Mía Trattoria & Wine Bar', 'content'=>'Un rincón íntimo y elegante dedicado a la alta cocina italiana y a la cultura del vino. Pastas artesanales hechas en casa, risottos trufados, carpaccios y una selección extraordinaria de etiquetas internacionales para maridajes inolvidables.', 'cocina'=>'Cocina Italiana de Autor & Wine Bar', 'horario'=>'', 'reserva_tipo'=>'web', 'reserva_val'=>'https://casadepiedraleon.mx', 'menu'=>'', 'thumb'=>''),
  array('title'=>'Lucio Ítalo-Argentino', 'content'=>'Una propuesta exquisita que entrelaza la tradición artesanal de las pastas y risottos italianos con la maestría de los cortes asados a la brasa argentina. Sabor contemporáneo en un entorno de lujo y distinción.', 'cocina'=>'Cocina Ítalo-Argentina de Autor', 'horario'=>'', 'reserva_tipo'=>'web', 'reserva_val'=>'https://grupomrl.com.mx/2025/lucio/', 'menu'=> get_template_directory_uri() . '/assets/pdfs/LUCIO-LEON-DIGITAL.pdf', 'thumb'=>''),
  array('title'=>'Argentilia', 'content'=>'Argentilia es el referente en alta cocina argentina en el Bajío, con cortes selectos a la parrilla de leña, empanadas caseras y una cava excepcional en un entorno de elegancia señorial.', 'cocina'=>'Alta Cocina Argentina & Parrilla Josper', 'horario'=>'', 'reserva_tipo'=>'whatsapp', 'reserva_val'=>'https://wa.link/e3s51k', 'menu'=>'https://argentilia.mx/leon/', 'thumb'=>''),
  array('title'=>'Sato Cocina Nikkei', 'content'=>'Fusión sublime entre la milenaria tradición culinaria japonesa y la vibrante cocina peruana. Omakase, nigiris de autor, ceviches y robatayaki con ingredientes premium en un ambiente minimalista de nivel internacional.', 'cocina'=>'Alta Cocina Japonesa & Nikkei', 'horario'=>'', 'reserva_tipo'=>'web', 'reserva_val'=>'https://satorestaurante.com.mx', 'menu'=>'https://satorestaurante.com.mx', 'thumb'=>''),
);
?>
